name: Frontend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  html-css-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check HTML files
        uses: Cyb3r-Jak3/html5validator-action@v0.4.0
        with:
          root: .

      - name: Check CSS files
        run: |
          sudo apt-get install -y curl
          curl -s -F "file=@style.css" https://jigsaw.w3.org/css-validator/validator
